
typedef struct mfci_in_b_t {
   uint32_t                    counter;                    //!< Счетчик контроля достоверности данных //(min:0 max:4294967295)
   mfci_in_25hz_b_t            mfci_in_25hz_b;             //!< Входные данные МФЦИ на частоте 25 Гц
   mfci_in_12hz_b_t            mfci_in_12hz_b;             //!< Входные данные МФЦИ на частоте 12.5 Гц
   mfci_in_6hz_b_t             mfci_in_6hz_b;              //!< Входные данные МФЦИ на частоте 6.25 Гц
   mfci_in_1hz_b_t             mfci_in_1hz_b;              //!< Входные данные МФЦИ на частоте 1 Гц
   mfci_in_blocks_crc_mkio_b_t blocks_crc_b[CRC_SA_COUNT]; //!< Входное сообщение МФЦИ c данными кадра БЛОКИ-КС (фрагмент 1-3, подадрес 26-28 МКИО-3.1)
} mfci_in_b_t;

// Входные данные МФЦИ на частоте 25 Гц
typedef struct mfci_in_25hz_b_t {
   uint32_t             counter; //!< Счетчик контроля достоверности данных //(min:0 max:4294967295)
   mfci_in_25hz_bis_b_t bis_b;   //!< Входные данные МФЦИ на частоте 25 Гц от БИС (подадреса 1-6 МКИО-3.1)
} mfci_in_25hz_b_t;

// Входные данные МФЦИ на частоте 25 Гц от БИС (подадреса 1-6 МКИО-3.1)
typedef struct mfci_in_25hz_bis_b_t {
   uint32_t         counter; //!< Счетчик контроля достоверности данных //(min:0 max:4294967295)
   mfci_in_sa_1_b_t sa_1_b;  //!< Входное сообщение МФЦИ, подадрес 1 МКИО-3.1
   mfci_in_sa_2_b_t sa_2_b;  //!< Входное сообщение МФЦИ, подадрес 2 МКИО-3.1
   mfci_in_sa_3_b_t sa_3_b;  //!< Входное сообщение МФЦИ, подадрес 3 МКИО-3.1
   mfci_in_sa_4_b_t sa_4_b;  //!< Входное сообщение МФЦИ, подадрес 4 МКИО-3.1
   mfci_in_sa_5_b_t sa_5_b;  //!< Входное сообщение МФЦИ, подадрес 5 МКИО-3.1
   mfci_in_sa_6_b_t sa_6_b;  //!< Входное сообщение МФЦИ, подадрес 6 МКИО-3.1
} mfci_in_25hz_bis_b_t;

// Входное сообщение МФЦИ, подадрес 1 МКИО-3.1 (25 Гц, передается постоянно)
typedef struct mfci_in_sa_1_b_t {
   uint16_t                 counter;           //!< Счетчик контроля достоверности данных //(min:0 max:65535 bits:4..19 lsb:1)
   uint16_t                 header_revision;   //!< Ревизия заголовочника (MFCI_IO_REVISION) //(min:1 max:65535 bits:4..19 lsb:1)
   mfci_signals_word_1_b_t  signals_word_1_b;  //!< Слово 1 сигнализации МФЦИ (сигналы ДВ)
   mfci_signals_word_2_b_t  signals_word_2_b;  //!< Слово 2 сигнализации МФЦИ (сигналы ДВ)
   mfci_signals_word_3_b_t  signals_word_3_b;  //!< Слово 3 сигнализации МФЦИ (сигналы ДВ)
   mfci_signals_word_4_b_t  signals_word_4_b;  //!< Слово 4 сигнализации МФЦИ (сигналы ДВ)
   mfci_signals_word_5_b_t  signals_word_5_b;  //!< Слово 5 сигнализации МФЦИ (сигналы ДВ)
   mfci_signals_word_6_b_t  signals_word_6_b;  //!< Слово 6 сигнализации МФЦИ (сигналы ДВ)
   mfci_signals_word_7_b_t  signals_word_7_b;  //!< Слово 7 сигнализации МФЦИ (сигналы ДВ)
   mfci_signals_word_8_b_t  signals_word_8_b;  //!< Слово 8 сигнализации МФЦИ (сигналы ДВ)
   mfci_signals_word_9_b_t  signals_word_9_b;  //!< Слово 9 сигнализации МФЦИ (сигналы ДВ)
   mfci_signals_word_10_b_t signals_word_10_b; //!< Слово 10 сигнализации МФЦИ (сигналы ДВ)
   mfci_signals_word_11_b_t signals_word_11_b; //!< Слово 11 сигнализации МФЦИ (сигналы ДВ)
   mfci_signals_word_12_b_t signals_word_12_b; //!< Слово 12 сигнализации МФЦИ (сигналы ДВ)
   mfci_signals_word_13_b_t signals_word_13_b; //!< Слово 13 сигнализации МФЦИ (сигналы ДВ)
   mfci_signals_word_14_b_t signals_word_14_b; //!< Слово 14 сигнализации МФЦИ (сигналы ДВ)
   mfci_signals_word_15_b_t signals_word_15_b; //!< Слово 15 сигнализации МФЦИ (сигналы ДВ)
   mfci_signals_word_16_b_t signals_word_16_b; //!< Слово 16 сигнализации МФЦИ (сигналы ДВ, ТОПЛ)
   mfci_signals_word_17_b_t signals_word_17_b; //!< Слово 17 сигнализации МФЦИ (сигналы ТОПЛ)
   mfci_signals_word_18_b_t signals_word_18_b; //!< Слово 18 сигнализации МФЦИ (сигналы ТОПЛ)
   mfci_signals_word_19_b_t signals_word_19_b; //!< Слово 19 сигнализации МФЦИ (сигналы ТОПЛ)
   mfci_signals_word_20_b_t signals_word_20_b; //!< Слово 20 сигнализации МФЦИ (сигналы ТОПЛ, ПКР)
   mfci_signals_word_21_b_t signals_word_21_b; //!< Слово 21 сигнализации МФЦИ (сигналы ПКР, САУ)
   mfci_signals_word_22_b_t signals_word_22_b; //!< Слово 22 сигнализации МФЦИ (сигналы САУ, АБСУ)
   mfci_signals_word_23_b_t signals_word_23_b; //!< Слово 23 сигнализации МФЦИ (сигналы АБСУ)
   mfci_signals_word_24_b_t signals_word_24_b; //!< Слово 24 сигнализации МФЦИ (сигналы АБСУ)
   mfci_signals_word_25_b_t signals_word_25_b; //!< Слово 25 сигнализации МФЦИ (сигналы АБСУ, СМК)
   mfci_signals_word_26_b_t signals_word_26_b; //!< Слово 26 сигнализации МФЦИ (сигналы СМК, СК, ТОРМ)
   mfci_signals_word_27_b_t signals_word_27_b; //!< Слово 27 сигнализации МФЦИ (сигналы ТОРМ, СЭС)
   mfci_signals_word_28_b_t signals_word_28_b; //!< Слово 28 сигнализации МФЦИ (сигналы СЭС)
   mfci_signals_word_29_b_t signals_word_29_b; //!< Слово 29 сигнализации МФЦИ (сигналы СЭС)
   mfci_signals_word_30_b_t signals_word_30_b; //!< Слово 30 сигнализации МФЦИ (сигналы ГС)
} mfci_in_sa_1_b_t;

//! Слово 1 сигнализации МФЦИ (сигналы ДВ)
typedef struct mfci_signals_word_1_b_t {
   uint16_t dv1_turb_overheating : 1; //!< [ДВ1-Д007] ДВ1 ОПОРА ПЕРЕГРЕВ (ДВ/С)
   uint16_t dv2_turb_overheating : 1; //!< [ДВ2-Д007] ДВ2 ОПОРА ПЕРЕГРЕВ (ДВ/С)
   uint16_t dv3_turb_overheating : 1; //!< [ДВ3-Д007] ДВ3 ОПОРА ПЕРЕГРЕВ (ДВ/С)
   uint16_t dv4_turb_overheating : 1; //!< [ДВ4-Д007] ДВ4 ОПОРА ПЕРЕГРЕВ (ДВ/С)
   uint16_t dv1_cooling_failure  : 1; //!< [ДВ1-Д008] ДВ1 ОХЛАЖД ОТКАЗ (ДВ/С)
   uint16_t dv2_cooling_failure  : 1; //!< [ДВ2-Д008] ДВ2 ОХЛАЖД ОТКАЗ (ДВ/С)
   uint16_t dv3_cooling_failure  : 1; //!< [ДВ3-Д008] ДВ3 ОХЛАЖД ОТКАЗ (ДВ/С)
   uint16_t dv4_cooling_failure  : 1; //!< [ДВ4-Д008] ДВ4 ОХЛАЖД ОТКАЗ (ДВ/С)
   uint16_t dv1_swarf            : 1; //!< [ДВ1-Д015] ДВ1 СТРУЖКА В МАСЛЕ (ДВ/С)
   uint16_t dv2_swarf            : 1; //!< [ДВ2-Д015] ДВ2 СТРУЖКА В МАСЛЕ (ДВ/С)
   uint16_t dv3_swarf            : 1; //!< [ДВ3-Д015] ДВ3 СТРУЖКА В МАСЛЕ (ДВ/С)
   uint16_t dv4_swarf            : 1; //!< [ДВ4-Д015] ДВ4 СТРУЖКА В МАСЛЕ (ДВ/С)
   uint16_t dv1_oil_low          : 1; //!< [ДВ1-Д017] ДВ1 МАСЛА МАЛО (ДВ/С)
   uint16_t dv2_oil_low          : 1; //!< [ДВ2-Д017] ДВ2 МАСЛА МАЛО (ДВ/С)
   uint16_t dv3_oil_low          : 1; //!< [ДВ3-Д017] ДВ3 МАСЛА МАЛО (ДВ/С)
   uint16_t dv4_oil_low          : 1; //!< [ДВ4-Д017] ДВ4 МАСЛА МАЛО (ДВ/С)
} mfci_signals_word_1_b_t;

//! Слово 2 сигнализации МФЦИ (сигналы ДВ)
typedef struct mfci_signals_word_2_b_t {
   uint16_t dv1_oil_high            : 1; //!< [ДВ1-Д018] ДВ1 МАСЛА МНОГО (ДВ/С)
   uint16_t dv2_oil_high            : 1; //!< [ДВ2-Д018] ДВ2 МАСЛА МНОГО (ДВ/С)
   uint16_t dv3_oil_high            : 1; //!< [ДВ3-Д018] ДВ3 МАСЛА МНОГО (ДВ/С)
   uint16_t dv4_oil_high            : 1; //!< [ДВ4-Д018] ДВ4 МАСЛА МНОГО (ДВ/С)
   uint16_t dv1_oil_pressure_in_low : 1; //!< [ДВ1-Д019] ДВ1 ДАВЛ МАСЛА МАЛО (ДВ/С)
   uint16_t dv2_oil_pressure_in_low : 1; //!< [ДВ2-Д019] ДВ2 ДАВЛ МАСЛА МАЛО (ДВ/С)
   uint16_t dv3_oil_pressure_in_low : 1; //!< [ДВ3-Д019] ДВ3 ДАВЛ МАСЛА МАЛО (ДВ/С)
   uint16_t dv4_oil_pressure_in_low : 1; //!< [ДВ4-Д019] ДВ4 ДАВЛ МАСЛА МАЛО (ДВ/С)
   uint16_t dv1_surge               : 1; //!< [ДВ1-Д020] ДВ1 ПОМПАЖ (ДВ/С)
   uint16_t dv2_surge               : 1; //!< [ДВ2-Д020] ДВ2 ПОМПАЖ (ДВ/С)
   uint16_t dv3_surge               : 1; //!< [ДВ3-Д020] ДВ3 ПОМПАЖ (ДВ/С)
   uint16_t dv4_surge               : 1; //!< [ДВ4-Д020] ДВ4 ПОМПАЖ (ДВ/С)
   uint16_t dv1_fuel_pressure_low   : 1; //!< [ДВ1-Д021] ДВ1 ДАВЛ ТОПЛ МАЛО (ДВ/С)
   uint16_t dv2_fuel_pressure_low   : 1; //!< [ДВ2-Д021] ДВ2 ДАВЛ ТОПЛ МАЛО (ДВ/С)
   uint16_t dv3_fuel_pressure_low   : 1; //!< [ДВ3-Д021] ДВ3 ДАВЛ ТОПЛ МАЛО (ДВ/С)
   uint16_t dv4_fuel_pressure_low   : 1; //!< [ДВ4-Д021] ДВ4 ДАВЛ ТОПЛ МАЛО (ДВ/С)
} mfci_signals_word_2_b_t;

//! Слово 3 сигнализации МФЦИ (сигналы ДВ)
typedef struct mfci_signals_word_3_b_t {
   uint16_t dv1_esud_healthy   : 1; //!< [ДВ1-Д023] ДВ1 ЭСУД ИСПРАВНА (ДВ/С)
   uint16_t dv2_esud_healthy   : 1; //!< [ДВ2-Д023] ДВ2 ЭСУД ИСПРАВНА (ДВ/С)
   uint16_t dv3_esud_healthy   : 1; //!< [ДВ3-Д023] ДВ3 ЭСУД ИСПРАВНА (ДВ/С)
   uint16_t dv4_esud_healthy   : 1; //!< [ДВ4-Д023] ДВ4 ЭСУД ИСПРАВНА (ДВ/С)
   uint16_t dv1_clogging       : 1; //!< [ДВ1-Д028] ДВ1 ТОПЛ ФИЛЬТР ЗАСОРЕН (ДВ/С)
   uint16_t dv2_clogging       : 1; //!< [ДВ2-Д028] ДВ2 ТОПЛ ФИЛЬТР ЗАСОРЕН (ДВ/С)
   uint16_t dv3_clogging       : 1; //!< [ДВ3-Д028] ДВ3 ТОПЛ ФИЛЬТР ЗАСОРЕН (ДВ/С)
   uint16_t dv4_clogging       : 1; //!< [ДВ4-Д028] ДВ4 ТОПЛ ФИЛЬТР ЗАСОРЕН (ДВ/С)
   uint16_t dv1_oil_temp_high  : 1; //!< [ДВ1-Д029] ДВ1 ТЕМПЕР МАСЛА ВХОДА ВЕЛИКА (ДВ/С)
   uint16_t dv2_oil_temp_high  : 1; //!< [ДВ2-Д029] ДВ2 ТЕМПЕР МАСЛА ВХОДА ВЕЛИКА (ДВ/С)
   uint16_t dv3_oil_temp_high  : 1; //!< [ДВ3-Д029] ДВ3 ТЕМПЕР МАСЛА ВХОДА ВЕЛИКА (ДВ/С)
   uint16_t dv4_oil_temp_high  : 1; //!< [ДВ4-Д029] ДВ4 ТЕМПЕР МАСЛА ВХОДА ВЕЛИКА (ДВ/С)
   uint16_t dv1_vibration_high : 1; //!< [ДВ1-Д030] ДВ1 ВИБР ОПАСНАЯ (ДВ/С)
   uint16_t dv2_vibration_high : 1; //!< [ДВ2-Д030] ДВ2 ВИБР ОПАСНАЯ (ДВ/С)
   uint16_t dv3_vibration_high : 1; //!< [ДВ3-Д030] ДВ3 ВИБР ОПАСНАЯ (ДВ/С)
   uint16_t dv4_vibration_high : 1; //!< [ДВ4-Д030] ДВ4 ВИБР ОПАСНАЯ (ДВ/С)
} mfci_signals_word_3_b_t;

//! Слово 4 сигнализации МФЦИ (сигналы ДВ)
typedef struct mfci_signals_word_4_b_t {
   uint16_t dv1_vna_failure              : 1; //!< [ДВ1-Д031] ДВ1 ОБОГРЕВ ВНА ОТКАЗ (ДВ/С)
   uint16_t dv2_vna_failure              : 1; //!< [ДВ2-Д031] ДВ2 ОБОГРЕВ ВНА ОТКАЗ (ДВ/С)
   uint16_t dv3_vna_failure              : 1; //!< [ДВ3-Д031] ДВ3 ОБОГРЕВ ВНА ОТКАЗ (ДВ/С)
   uint16_t dv4_vna_failure              : 1; //!< [ДВ4-Д031] ДВ4 ОБОГРЕВ ВНА ОТКАЗ (ДВ/С)
   uint16_t dv1_bearing_temperature_high : 1; //!< [ДВ1-Д032] ДВ1 ТЕМПЕР ПОДШ ВЕЛИКА (ДВ/С)
   uint16_t dv2_bearing_temperature_high : 1; //!< [ДВ2-Д032] ДВ2 ТЕМПЕР ПОДШ ВЕЛИКА (ДВ/С)
   uint16_t dv3_bearing_temperature_high : 1; //!< [ДВ3-Д032] ДВ3 ТЕМПЕР ПОДШ ВЕЛИКА (ДВ/С)
   uint16_t dv4_bearing_temperature_high : 1; //!< [ДВ4-Д032] ДВ4 ТЕМПЕР ПОДШ ВЕЛИКА (ДВ/С)
   uint16_t dv1_no_correction            : 1; //!< [ДВ1-Д033] ДВ1 НЕТ КОРРЕКЦИИ ОТ (ДВ/С)
   uint16_t dv2_no_correction            : 1; //!< [ДВ2-Д033] ДВ2 НЕТ КОРРЕКЦИИ ОТ (ДВ/С)
   uint16_t dv3_no_correction            : 1; //!< [ДВ3-Д033] ДВ3 НЕТ КОРРЕКЦИИ ОТ (ДВ/С)
   uint16_t dv4_no_correction            : 1; //!< [ДВ4-Д033] ДВ4 НЕТ КОРРЕКЦИИ ОТ (ДВ/С)
   uint16_t dv1_intake_healthy           : 1; //!< [ДВ1-Д034] ДВ1 АУ ВЗ ИСПРАВНА (ДВ/С)
   uint16_t dv2_intake_healthy           : 1; //!< [ДВ2-Д034] ДВ2 АУ ВЗ ИСПРАВНА (ДВ/С)
   uint16_t dv3_intake_healthy           : 1; //!< [ДВ3-Д034] ДВ3 АУ ВЗ ИСПРАВНА (ДВ/С)
   uint16_t dv4_intake_healthy           : 1; //!< [ДВ4-Д034] ДВ4 АУ ВЗ ИСПРАВНА (ДВ/С)
} mfci_signals_word_4_b_t;

//! Слово 5 сигнализации МФЦИ (сигналы ДВ)
typedef struct mfci_signals_word_5_b_t {
   uint16_t dv1_intake_test           : 1; //!< [ДВ1-Д035] ДВ1 АУ ВЗ КОНТРОЛЬ (ДВ/С)
   uint16_t dv2_intake_test           : 1; //!< [ДВ2-Д035] ДВ2 АУ ВЗ КОНТРОЛЬ (ДВ/С)
   uint16_t dv3_intake_test           : 1; //!< [ДВ3-Д035] ДВ3 АУ ВЗ КОНТРОЛЬ (ДВ/С)
   uint16_t dv4_intake_test           : 1; //!< [ДВ4-Д035] ДВ4 АУ ВЗ КОНТРОЛЬ (ДВ/С)
   uint16_t dv1_throttle_afterburning : 1; //!< [ДВ1-Д036] ДВ1 ДРОССЕЛИР С ФОРСАЖЕМ (ДВ/С)
   uint16_t dv2_throttle_afterburning : 1; //!< [ДВ2-Д036] ДВ2 ДРОССЕЛИР С ФОРСАЖЕМ (ДВ/С)
   uint16_t dv3_throttle_afterburning : 1; //!< [ДВ3-Д036] ДВ3 ДРОССЕЛИР С ФОРСАЖЕМ (ДВ/С)
   uint16_t dv4_throttle_afterburning : 1; //!< [ДВ4-Д036] ДВ4 ДРОССЕЛИР С ФОРСАЖЕМ (ДВ/С)
   uint16_t dv1_turn_off              : 1; //!< [ДВ1-Д037] ДВ1 ВЫКЛЮЧИ (ДВ/С)
   uint16_t dv2_turn_off              : 1; //!< [ДВ2-Д037] ДВ2 ВЫКЛЮЧИ (ДВ/С)
   uint16_t dv3_turn_off              : 1; //!< [ДВ3-Д037] ДВ3 ВЫКЛЮЧИ (ДВ/С)
   uint16_t dv4_turn_off              : 1; //!< [ДВ4-Д037] ДВ4 ВЫКЛЮЧИ (ДВ/С)
   uint16_t dv1_intake_failure        : 1; //!< [ДВ1-Д039] ДВ1 АУ ВЗ НЕИСПР (ДВ/С)
   uint16_t dv2_intake_failure        : 1; //!< [ДВ2-Д039] ДВ2 АУ ВЗ НЕИСПР (ДВ/С)
   uint16_t dv3_intake_failure        : 1; //!< [ДВ3-Д039] ДВ3 АУ ВЗ НЕИСПР (ДВ/С)
   uint16_t dv4_intake_failure        : 1; //!< [ДВ4-Д039] ДВ4 АУ ВЗ НЕИСПР (ДВ/С)
} mfci_signals_word_5_b_t;

//! Слово 6 сигнализации МФЦИ (сигналы ДВ)
typedef struct mfci_signals_word_6_b_t {
   uint16_t dv1_wedge_failure            : 1; //!< [ДВ1-Д040] ДВ1 АУ КЛИНОМ ОТКАЗ (ДВ/С)
   uint16_t dv2_wedge_failure            : 1; //!< [ДВ2-Д040] ДВ2 АУ КЛИНОМ ОТКАЗ (ДВ/С)
   uint16_t dv3_wedge_failure            : 1; //!< [ДВ3-Д040] ДВ3 АУ КЛИНОМ ОТКАЗ (ДВ/С)
   uint16_t dv4_wedge_failure            : 1; //!< [ДВ4-Д040] ДВ4 АУ КЛИНОМ ОТКАЗ (ДВ/С)
   uint16_t dv1_valve_failure            : 1; //!< [ДВ1-Д041] ДВ1 АУ СТВОРОК ОТКАЗ (ДВ/С)
   uint16_t dv2_valve_failure            : 1; //!< [ДВ2-Д041] ДВ2 АУ СТВОРОК ОТКАЗ (ДВ/С)
   uint16_t dv3_valve_failure            : 1; //!< [ДВ3-Д041] ДВ3 АУ СТВОРОК ОТКАЗ (ДВ/С)
   uint16_t dv4_valve_failure            : 1; //!< [ДВ4-Д041] ДВ4 АУ СТВОРОК ОТКАЗ (ДВ/С)
   uint16_t dv1_n_sd_high                : 1; //!< [ДВ1-Д042] ДВ1 ОБОРОТЫ СД ОПАСНЫЕ (ДВ/С)
   uint16_t dv2_n_sd_high                : 1; //!< [ДВ2-Д042] ДВ2 ОБОРОТЫ СД ОПАСНЫЕ (ДВ/С)
   uint16_t dv3_n_sd_high                : 1; //!< [ДВ3-Д042] ДВ3 ОБОРОТЫ СД ОПАСНЫЕ (ДВ/С)
   uint16_t dv4_n_sd_high                : 1; //!< [ДВ4-Д042] ДВ4 ОБОРОТЫ СД ОПАСНЫЕ (ДВ/С)
   uint16_t dv1_oil_temperature_out_high : 1; //!< [ДВ1-Д044] ДВ1 ТЕМПЕР МАСЛА ВЫХОДА ВЕЛИКА (ДВ/С)
   uint16_t dv2_oil_temperature_out_high : 1; //!< [ДВ2-Д044] ДВ2 ТЕМПЕР МАСЛА ВЫХОДА ВЕЛИКА (ДВ/С)
   uint16_t dv3_oil_temperature_out_high : 1; //!< [ДВ3-Д044] ДВ3 ТЕМПЕР МАСЛА ВЫХОДА ВЕЛИКА (ДВ/С)
   uint16_t dv4_oil_temperature_out_high : 1; //!< [ДВ4-Д044] ДВ4 ТЕМПЕР МАСЛА ВЫХОДА ВЕЛИКА (ДВ/С)
} mfci_signals_word_6_b_t;

//! Слово 7 сигнализации МФЦИ (сигналы ДВ)
typedef struct mfci_signals_word_7_b_t {
   uint16_t dv1_no_afterburning       : 1; //!< [ДВ1-Д045] ДВ1 НЕТ ФОРСАЖА/ ПОВТОРИ ФОРСАЖ (ДВ/С)
   uint16_t dv2_no_afterburning       : 1; //!< [ДВ2-Д045] ДВ2 НЕТ ФОРСАЖА/ ПОВТОРИ ФОРСАЖ (ДВ/С)
   uint16_t dv3_no_afterburning       : 1; //!< [ДВ3-Д045] ДВ3 НЕТ ФОРСАЖА/ ПОВТОРИ ФОРСАЖ (ДВ/С)
   uint16_t dv4_no_afterburning       : 1; //!< [ДВ4-Д045] ДВ4 НЕТ ФОРСАЖА/ ПОВТОРИ ФОРСАЖ (ДВ/С)
   uint16_t dv1_oil_pressure_gp22_low : 1; //!< [ДВ1-Д046] ДВ1 ДАВЛ МАСЛА ГП МАЛО (ДВ/С)
   uint16_t dv2_oil_pressure_gp22_low : 1; //!< [ДВ2-Д046] ДВ2 ДАВЛ МАСЛА ГП МАЛО (ДВ/С)
   uint16_t dv3_oil_pressure_gp22_low : 1; //!< [ДВ3-Д046] ДВ3 ДАВЛ МАСЛА ГП МАЛО (ДВ/С)
   uint16_t dv4_oil_pressure_gp22_low : 1; //!< [ДВ4-Д046] ДВ4 ДАВЛ МАСЛА ГП МАЛО (ДВ/С)
   uint16_t dv1_hydraulic_lock        : 1; //!< [ДВ1-Д047] ДВ1 ГИДРОУПОР ВКЛЮЧЕН (ДВ/С)
   uint16_t dv2_hydraulic_lock        : 1; //!< [ДВ2-Д047] ДВ2 ГИДРОУПОР ВКЛЮЧЕН (ДВ/С)
   uint16_t dv3_hydraulic_lock        : 1; //!< [ДВ3-Д047] ДВ3 ГИДРОУПОР ВКЛЮЧЕН (ДВ/С)
   uint16_t dv4_hydraulic_lock        : 1; //!< [ДВ4-Д047] ДВ4 ГИДРОУПОР ВКЛЮЧЕН (ДВ/С)
   uint16_t dv1_oil_pressure_gsbk_low : 1; //!< [ДВ1-Д049] ДВ1 ДАВЛ МАСЛА ГСБК МАЛО (ДВ/С)
   uint16_t dv2_oil_pressure_gsbk_low : 1; //!< [ДВ2-Д049] ДВ2 ДАВЛ МАСЛА ГСБК МАЛО (ДВ/С)
   uint16_t dv3_oil_pressure_gsbk_low : 1; //!< [ДВ3-Д049] ДВ3 ДАВЛ МАСЛА ГСБК МАЛО (ДВ/С)
   uint16_t dv4_oil_pressure_gsbk_low : 1; //!< [ДВ4-Д049] ДВ4 ДАВЛ МАСЛА ГСБК МАЛО (ДВ/С)
} mfci_signals_word_7_b_t;

//! Слово 8 сигнализации МФЦИ (сигналы ДВ)
typedef struct mfci_signals_word_8_b_t {
   uint16_t dv1_fuel_temperature_tmt_high : 1; //!< [ДВ1-Д055] ДВ1 ТЕМПЕР ТОПЛ ВЕЛИКА (ДВ/С)
   uint16_t dv2_fuel_temperature_tmt_high : 1; //!< [ДВ2-Д055] ДВ2 ТЕМПЕР ТОПЛ ВЕЛИКА (ДВ/С)
   uint16_t dv3_fuel_temperature_tmt_high : 1; //!< [ДВ3-Д055] ДВ3 ТЕМПЕР ТОПЛ ВЕЛИКА (ДВ/С)
   uint16_t dv4_fuel_temperature_tmt_high : 1; //!< [ДВ4-Д055] ДВ4 ТЕМПЕР ТОПЛ ВЕЛИКА (ДВ/С)
   uint16_t dv1_starter_high              : 1; //!< [ДВ1-Д056] ДВ1 ОБОРОТЫ СТАРТЕРА ОПАСНЫЕ (ДВ/С)
   uint16_t dv2_starter_high              : 1; //!< [ДВ2-Д056] ДВ2 ОБОРОТЫ СТАРТЕРА ОПАСНЫЕ (ДВ/С)
   uint16_t dv3_starter_high              : 1; //!< [ДВ3-Д056] ДВ3 ОБОРОТЫ СТАРТЕРА ОПАСНЫЕ (ДВ/С)
   uint16_t dv4_starter_high              : 1; //!< [ДВ4-Д056] ДВ4 ОБОРОТЫ СТАРТЕРА ОПАСНЫЕ (ДВ/С)
   uint16_t dv1_vpt_pressure_low          : 1; //!< [ДВ1-Д057] ДВ1 ДАВЛ ВПТ МАЛО (ДВ/С)
   uint16_t dv2_vpt_pressure_low          : 1; //!< [ДВ2-Д057] ДВ2 ДАВЛ ВПТ МАЛО (ДВ/С)
   uint16_t dv3_vpt_pressure_low          : 1; //!< [ДВ3-Д057] ДВ3 ДАВЛ ВПТ МАЛО (ДВ/С)
   uint16_t dv4_vpt_pressure_low          : 1; //!< [ДВ4-Д057] ДВ4 ДАВЛ ВПТ МАЛО (ДВ/С)
   uint16_t dv1_breather_pressure_high    : 1; //!< [ДВ1-Д058] ДВ1 ДАВЛ СУФЛИР ПОВЫШЕН (ДВ/С)
   uint16_t dv2_breather_pressure_high    : 1; //!< [ДВ2-Д058] ДВ2 ДАВЛ СУФЛИР ПОВЫШЕН (ДВ/С)
   uint16_t dv3_breather_pressure_high    : 1; //!< [ДВ3-Д058] ДВ3 ДАВЛ СУФЛИР ПОВЫШЕН (ДВ/С)
   uint16_t dv4_breather_pressure_high    : 1; //!< [ДВ4-Д058] ДВ4 ДАВЛ СУФЛИР ПОВЫШЕН (ДВ/С)
} mfci_signals_word_8_b_t;

//! Слово 9 сигнализации МФЦИ (сигналы ДВ)
typedef struct mfci_signals_word_9_b_t {
   uint16_t dv1_start_failure_on_land    : 1; //!< [ДВ1-Д061] ДВ1 ЭСУД НЕИСПР (ЗАП ЗЕМ ОТКАЗ, СОСТ)
   uint16_t dv2_start_failure_on_land    : 1; //!< [ДВ2-Д061] ДВ2 ЭСУД НЕИСПР (ЗАП ЗЕМ ОТКАЗ, СОСТ)
   uint16_t dv3_start_failure_on_land    : 1; //!< [ДВ3-Д061] ДВ3 ЭСУД НЕИСПР (ЗАП ЗЕМ ОТКАЗ, СОСТ)
   uint16_t dv4_start_failure_on_land    : 1; //!< [ДВ4-Д061] ДВ4 ЭСУД НЕИСПР (ЗАП ЗЕМ ОТКАЗ, СОСТ)
   uint16_t dv1_start_failure_in_air     : 1; //!< [ДВ1-Д062] ДВ1 ЭСУД НЕИСПР (ЗАП ВОЗД ОТКАЗ, СОСТ)
   uint16_t dv2_start_failure_in_air     : 1; //!< [ДВ2-Д062] ДВ2 ЭСУД НЕИСПР (ЗАП ВОЗД ОТКАЗ, СОСТ)
   uint16_t dv3_start_failure_in_air     : 1; //!< [ДВ3-Д062] ДВ3 ЭСУД НЕИСПР (ЗАП ВОЗД ОТКАЗ, СОСТ)
   uint16_t dv4_start_failure_in_air     : 1; //!< [ДВ4-Д062] ДВ4 ЭСУД НЕИСПР (ЗАП ВОЗД ОТКАЗ, СОСТ)
   uint16_t dv1_gas_temp_control_failure : 1; //!< [ДВ1-Д063] ДВ1 ЭСУД НЕИСПР (ОГРАН ТГ ОТКАЗ, СОСТ)
   uint16_t dv2_gas_temp_control_failure : 1; //!< [ДВ2-Д063] ДВ2 ЭСУД НЕИСПР (ОГРАН ТГ ОТКАЗ, СОСТ)
   uint16_t dv3_gas_temp_control_failure : 1; //!< [ДВ3-Д063] ДВ3 ЭСУД НЕИСПР (ОГРАН ТГ ОТКАЗ, СОСТ)
   uint16_t dv4_gas_temp_control_failure : 1; //!< [ДВ4-Д063] ДВ4 ЭСУД НЕИСПР (ОГРАН ТГ ОТКАЗ, СОСТ)
   uint16_t dv1_n2_control_failure       : 1; //!< [ДВ1-Д064] ДВ1 ЭСУД НЕИСПР (ОГРАН ВД ОТКАЗ, СОСТ)
   uint16_t dv2_n2_control_failure       : 1; //!< [ДВ2-Д064] ДВ2 ЭСУД НЕИСПР (ОГРАН ВД ОТКАЗ, СОСТ)
   uint16_t dv3_n2_control_failure       : 1; //!< [ДВ3-Д064] ДВ3 ЭСУД НЕИСПР (ОГРАН ВД ОТКАЗ, СОСТ)
   uint16_t dv4_n2_control_failure       : 1; //!< [ДВ4-Д064] ДВ4 ЭСУД НЕИСПР (ОГРАН ВД ОТКАЗ, СОСТ)
} mfci_signals_word_9_b_t;

//! Слово 10 сигнализации МФЦИ (сигналы ДВ)
typedef struct mfci_signals_word_10_b_t {
   uint16_t dv1_n1_control_failure           : 1; //!< [ДВ1-Д065] ДВ1 ЭСУД НЕИСПР (УПРАВЛ НД ОТКАЗ, СОСТ)
   uint16_t dv2_n1_control_failure           : 1; //!< [ДВ2-Д065] ДВ2 ЭСУД НЕИСПР (УПРАВЛ НД ОТКАЗ, СОСТ)
   uint16_t dv3_n1_control_failure           : 1; //!< [ДВ3-Д065] ДВ3 ЭСУД НЕИСПР (УПРАВЛ НД ОТКАЗ, СОСТ)
   uint16_t dv4_n1_control_failure           : 1; //!< [ДВ4-Д065] ДВ4 ЭСУД НЕИСПР (УПРАВЛ НД ОТКАЗ, СОСТ)
   uint16_t dv1_afterburning_control_failure : 1; //!< [ДВ1-Д066] ДВ1 ЭСУД НЕИСПР (УПР ФОРСАЖЕМ ОТКАЗ, СОСТ)
   uint16_t dv2_afterburning_control_failure : 1; //!< [ДВ2-Д066] ДВ2 ЭСУД НЕИСПР (УПР ФОРСАЖЕМ ОТКАЗ, СОСТ)
   uint16_t dv3_afterburning_control_failure : 1; //!< [ДВ3-Д066] ДВ3 ЭСУД НЕИСПР (УПР ФОРСАЖЕМ ОТКАЗ, СОСТ)
   uint16_t dv4_afterburning_control_failure : 1; //!< [ДВ4-Д066] ДВ4 ЭСУД НЕИСПР (УПР ФОРСАЖЕМ ОТКАЗ, СОСТ)
   uint16_t dv1_antisurge_control_failure    : 1; //!< [ДВ1-Д067] ДВ1 ЭСУД НЕИСПР (ППЗ ОТКАЗ, СОСТ)
   uint16_t dv2_antisurge_control_failure    : 1; //!< [ДВ2-Д067] ДВ2 ЭСУД НЕИСПР (ППЗ ОТКАЗ, СОСТ)
   uint16_t dv3_antisurge_control_failure    : 1; //!< [ДВ3-Д067] ДВ3 ЭСУД НЕИСПР (ППЗ ОТКАЗ, СОСТ)
   uint16_t dv4_antisurge_control_failure    : 1; //!< [ДВ4-Д067] ДВ4 ЭСУД НЕИСПР (ППЗ ОТКАЗ, СОСТ)
   uint16_t dv1_cooling_control_failure      : 1; //!< [ДВ1-Д068] ДВ1 УПР ОХЛ ТУРБИНЫ ОТКАЗ (СОСТ)
   uint16_t dv2_cooling_control_failure      : 1; //!< [ДВ2-Д068] ДВ2 УПР ОХЛ ТУРБИНЫ ОТКАЗ (СОСТ)
   uint16_t dv3_cooling_control_failure      : 1; //!< [ДВ3-Д068] ДВ3 УПР ОХЛ ТУРБИНЫ ОТКАЗ (СОСТ)
   uint16_t dv4_cooling_control_failure      : 1; //!< [ДВ4-Д068] ДВ4 УПР ОХЛ ТУРБИНЫ ОТКАЗ (СОСТ)
} mfci_signals_word_10_b_t;

//! Слово 11 сигнализации МФЦИ (сигналы ДВ)
typedef struct mfci_signals_word_11_b_t {
   uint16_t dv1_lock_control_failure       : 1; //!< [ДВ1-Д069] ДВ1 ЭСУД НЕИСПР (УПР ГИДРОУПОР ОТКАЗ, СОСТ)
   uint16_t dv2_lock_control_failure       : 1; //!< [ДВ2-Д069] ДВ2 ЭСУД НЕИСПР (УПР ГИДРОУПОР ОТКАЗ, СОСТ)
   uint16_t dv3_lock_control_failure       : 1; //!< [ДВ3-Д069] ДВ3 ЭСУД НЕИСПР (УПР ГИДРОУПОР ОТКАЗ, СОСТ)
   uint16_t dv4_lock_control_failure       : 1; //!< [ДВ4-Д069] ДВ4 ЭСУД НЕИСПР (УПР ГИДРОУПОР ОТКАЗ, СОСТ)
   uint16_t dv1_kpv_control_failure        : 1; //!< [ДВ1-Д070] ДВ1 УПР КПВ СД ОТКАЗ (СОСТ)
   uint16_t dv2_kpv_control_failure        : 1; //!< [ДВ2-Д070] ДВ2 УПР КПВ СД ОТКАЗ (СОСТ)
   uint16_t dv3_kpv_control_failure        : 1; //!< [ДВ3-Д070] ДВ3 УПР КПВ СД ОТКАЗ (СОСТ)
   uint16_t dv4_kpv_control_failure        : 1; //!< [ДВ4-Д070] ДВ4 УПР КПВ СД ОТКАЗ (СОСТ)
   uint16_t dv1_nozzle_control_failure     : 1; //!< [ДВ1-Д071] ДВ1 ЭСУД НЕИСПР (УПР СОПЛОМ ОТКАЗ, СОСТ)
   uint16_t dv2_nozzle_control_failure     : 1; //!< [ДВ2-Д071] ДВ2 ЭСУД НЕИСПР (УПР СОПЛОМ ОТКАЗ, СОСТ)
   uint16_t dv3_nozzle_control_failure     : 1; //!< [ДВ3-Д071] ДВ3 ЭСУД НЕИСПР (УПР СОПЛОМ ОТКАЗ, СОСТ)
   uint16_t dv4_nozzle_control_failure     : 1; //!< [ДВ4-Д071] ДВ4 ЭСУД НЕИСПР (УПР СОПЛОМ ОТКАЗ, СОСТ)
   uint16_t dv1_start_failed_main_switcher : 1; //!< [ДВ1-Д072] ДВ1 ЗАПУСК ПРЕКРАЩЕН (НЕТ ГЛАВНЫЙ ВЫКЛ, ДВ/С)
   uint16_t dv2_start_failed_main_switcher : 1; //!< [ДВ2-Д072] ДВ2 ЗАПУСК ПРЕКРАЩЕН (НЕТ ГЛАВНЫЙ ВЫКЛ, ДВ/С)
   uint16_t dv3_start_failed_main_switcher : 1; //!< [ДВ3-Д072] ДВ3 ЗАПУСК ПРЕКРАЩЕН (НЕТ ГЛАВНЫЙ ВЫКЛ, ДВ/С)
   uint16_t dv4_start_failed_main_switcher : 1; //!< [ДВ4-Д072] ДВ4 ЗАПУСК ПРЕКРАЩЕН (НЕТ ГЛАВНЫЙ ВЫКЛ, ДВ/С)
} mfci_signals_word_11_b_t;

//! Слово 12 сигнализации МФЦИ (сигналы ДВ)
typedef struct mfci_signals_word_12_b_t {
   uint16_t dv1_start_failed_starter       : 1; //!< [ДВ1-Д073] ДВ1 ЗАПУСК ПРЕКРАЩЕН (ОБОРОТЫ СТАРТЕРА ПРЕДЕЛ, ДВ/С)
   uint16_t dv2_start_failed_starter       : 1; //!< [ДВ2-Д073] ДВ2 ЗАПУСК ПРЕКРАЩЕН (ОБОРОТЫ СТАРТЕРА ПРЕДЕЛ, ДВ/С)
   uint16_t dv3_start_failed_starter       : 1; //!< [ДВ3-Д073] ДВ3 ЗАПУСК ПРЕКРАЩЕН (ОБОРОТЫ СТАРТЕРА ПРЕДЕЛ, ДВ/С)
   uint16_t dv4_start_failed_starter       : 1; //!< [ДВ4-Д073] ДВ4 ЗАПУСК ПРЕКРАЩЕН (ОБОРОТЫ СТАРТЕРА ПРЕДЕЛ, ДВ/С)
   uint16_t dv1_start_failed_stop_switcher : 1; //!< [ДВ1-Д074] ДВ1 ЗАПУСК ПРЕКРАЩЕН (СТОП-КРАН НЕ ОТКРЫТ, ДВ/С)
   uint16_t dv2_start_failed_stop_switcher : 1; //!< [ДВ2-Д074] ДВ2 ЗАПУСК ПРЕКРАЩЕН (СТОП-КРАН НЕ ОТКРЫТ, ДВ/С)
   uint16_t dv3_start_failed_stop_switcher : 1; //!< [ДВ3-Д074] ДВ3 ЗАПУСК ПРЕКРАЩЕН (СТОП-КРАН НЕ ОТКРЫТ, ДВ/С)
   uint16_t dv4_start_failed_stop_switcher : 1; //!< [ДВ4-Д074] ДВ4 ЗАПУСК ПРЕКРАЩЕН (СТОП-КРАН НЕ ОТКРЫТ, ДВ/С)
   uint16_t dv1_start_failed_kpv           : 1; //!< [ДВ1-Д075] ДВ1 ЗАПУСК ПРЕКРАЩЕН (КПВ ВД НЕ ОТКР, ДВ/С)
   uint16_t dv2_start_failed_kpv           : 1; //!< [ДВ2-Д075] ДВ2 ЗАПУСК ПРЕКРАЩЕН (КПВ ВД НЕ ОТКР, ДВ/С)
   uint16_t dv3_start_failed_kpv           : 1; //!< [ДВ3-Д075] ДВ3 ЗАПУСК ПРЕКРАЩЕН (КПВ ВД НЕ ОТКР, ДВ/С)
   uint16_t dv4_start_failed_kpv           : 1; //!< [ДВ4-Д075] ДВ4 ЗАПУСК ПРЕКРАЩЕН (КПВ ВД НЕ ОТКР, ДВ/С)
   uint16_t dv1_start_failed_supply_115    : 1; //!< [ДВ1-Д076] ДВ1 ЗАПУСК ПРЕКРАЩЕН (115В НЕ В НОРМЕ, ДВ/С)
   uint16_t dv2_start_failed_supply_115    : 1; //!< [ДВ2-Д076] ДВ2 ЗАПУСК ПРЕКРАЩЕН (115В НЕ В НОРМЕ, ДВ/С)
   uint16_t dv3_start_failed_supply_115    : 1; //!< [ДВ3-Д076] ДВ3 ЗАПУСК ПРЕКРАЩЕН (115В НЕ В НОРМЕ, ДВ/С)
   uint16_t dv4_start_failed_supply_115    : 1; //!< [ДВ4-Д076] ДВ4 ЗАПУСК ПРЕКРАЩЕН (115В НЕ В НОРМЕ, ДВ/С)
} mfci_signals_word_12_b_t;

//! Слово 13 сигнализации МФЦИ (сигналы ДВ)
typedef struct mfci_signals_word_13_b_t {
   uint16_t dv1_start_failed_control  : 1; //!< [ДВ1-Д077] ДВ1 ЗАПУСК ПРЕКРАЩЕН (ЭСУД ОТКАЗ, ДВ/С)
   uint16_t dv2_start_failed_control  : 1; //!< [ДВ2-Д077] ДВ2 ЗАПУСК ПРЕКРАЩЕН (ЭСУД ОТКАЗ, ДВ/С)
   uint16_t dv3_start_failed_control  : 1; //!< [ДВ3-Д077] ДВ3 ЗАПУСК ПРЕКРАЩЕН (ЭСУД ОТКАЗ, ДВ/С)
   uint16_t dv4_start_failed_control  : 1; //!< [ДВ4-Д077] ДВ4 ЗАПУСК ПРЕКРАЩЕН (ЭСУД ОТКАЗ, ДВ/С)
   uint16_t dv1_start_failed_spinup   : 1; //!< [ДВ1-Д078] ДВ1 ЗАПУСК ПРЕКРАЩЕН (НЕТ РАСКРУТКИ, ДВ/С)
   uint16_t dv2_start_failed_spinup   : 1; //!< [ДВ2-Д078] ДВ2 ЗАПУСК ПРЕКРАЩЕН (НЕТ РАСКРУТКИ, ДВ/С)
   uint16_t dv3_start_failed_spinup   : 1; //!< [ДВ3-Д078] ДВ3 ЗАПУСК ПРЕКРАЩЕН (НЕТ РАСКРУТКИ, ДВ/С)
   uint16_t dv4_start_failed_spinup   : 1; //!< [ДВ4-Д078] ДВ4 ЗАПУСК ПРЕКРАЩЕН (НЕТ РАСКРУТКИ, ДВ/С)
   uint16_t dv1_start_failed_gas_temp : 1; //!< [ДВ1-Д079] ДВ1 ЗАПУСК ПРЕКРАЩЕН (ТЕМПЕР ГАЗА ОПАСНАЯ, ДВ/С)
   uint16_t dv2_start_failed_gas_temp : 1; //!< [ДВ2-Д079] ДВ2 ЗАПУСК ПРЕКРАЩЕН (ТЕМПЕР ГАЗА ОПАСНАЯ, ДВ/С)
   uint16_t dv3_start_failed_gas_temp : 1; //!< [ДВ3-Д079] ДВ3 ЗАПУСК ПРЕКРАЩЕН (ТЕМПЕР ГАЗА ОПАСНАЯ, ДВ/С)
   uint16_t dv4_start_failed_gas_temp : 1; //!< [ДВ4-Д079] ДВ4 ЗАПУСК ПРЕКРАЩЕН (ТЕМПЕР ГАЗА ОПАСНАЯ, ДВ/С)
   uint16_t dv1_start_failed_handup   : 1; //!< [ДВ1-Д080] ДВ1 ЗАПУСК ПРЕКРАЩЕН (ВРЕМЯ ЗАП ПРЕВЫШ, ДВ/С)
   uint16_t dv2_start_failed_handup   : 1; //!< [ДВ2-Д080] ДВ2 ЗАПУСК ПРЕКРАЩЕН (ВРЕМЯ ЗАП ПРЕВЫШ, ДВ/С)
   uint16_t dv3_start_failed_handup   : 1; //!< [ДВ3-Д080] ДВ3 ЗАПУСК ПРЕКРАЩЕН (ВРЕМЯ ЗАП ПРЕВЫШ, ДВ/С)
   uint16_t dv4_start_failed_handup   : 1; //!< [ДВ4-Д080] ДВ4 ЗАПУСК ПРЕКРАЩЕН (ВРЕМЯ ЗАП ПРЕВЫШ, ДВ/С)
} mfci_signals_word_13_b_t;

//! Слово 14 сигнализации МФЦИ (сигналы ДВ)
typedef struct mfci_signals_word_14_b_t {
   uint16_t dv1_start_failed_ignition : 1; //!< [ДВ1-Д081] ДВ1 ЗАПУСК ПРЕКРАЩЕН (НЕТ РОЗЖИГА, ДВ/С)
   uint16_t dv2_start_failed_ignition : 1; //!< [ДВ2-Д081] ДВ2 ЗАПУСК ПРЕКРАЩЕН (НЕТ РОЗЖИГА, ДВ/С)
   uint16_t dv3_start_failed_ignition : 1; //!< [ДВ3-Д081] ДВ3 ЗАПУСК ПРЕКРАЩЕН (НЕТ РОЗЖИГА, ДВ/С)
   uint16_t dv4_start_failed_ignition : 1; //!< [ДВ4-Д081] ДВ4 ЗАПУСК ПРЕКРАЩЕН (НЕТ РОЗЖИГА, ДВ/С)
   uint16_t dv1_kpv_undefined         : 1; //!< [ДВ1-Л001] ДВ1 КОМПРЕСС ОТКАЗ (ДВ/С)
   uint16_t dv2_kpv_undefined         : 1; //!< [ДВ2-Л001] ДВ2 КОМПРЕСС ОТКАЗ (ДВ/С)
   uint16_t dv3_kpv_undefined         : 1; //!< [ДВ3-Л001] ДВ3 КОМПРЕСС ОТКАЗ (ДВ/С)
   uint16_t dv4_kpv_undefined         : 1; //!< [ДВ4-Л001] ДВ4 КОМПРЕСС ОТКАЗ (ДВ/С)
   uint16_t dv1_esud_failure          : 1; //!< [ДВ1-Л002] ДВ1 ЭСУД НЕИСПР (ДВ/С)
   uint16_t dv2_esud_failure          : 1; //!< [ДВ2-Л002] ДВ2 ЭСУД НЕИСПР (ДВ/С)
   uint16_t dv3_esud_failure          : 1; //!< [ДВ3-Л002] ДВ3 ЭСУД НЕИСПР (ДВ/С)
   uint16_t dv4_esud_failure          : 1; //!< [ДВ4-Л002] ДВ4 ЭСУД НЕИСПР (ДВ/С)
   uint16_t dv1_gas_temp_high_danger  : 1; //!< [ДВ1-Л003] ДВ1 ТЕМПЕР ГАЗА ОПАСНАЯ (ДВ/С)
   uint16_t dv2_gas_temp_high_danger  : 1; //!< [ДВ2-Л003] ДВ2 ТЕМПЕР ГАЗА ОПАСНАЯ (ДВ/С)
   uint16_t dv3_gas_temp_high_danger  : 1; //!< [ДВ3-Л003] ДВ3 ТЕМПЕР ГАЗА ОПАСНАЯ (ДВ/С)
   uint16_t dv4_gas_temp_high_danger  : 1; //!< [ДВ4-Л003] ДВ4 ТЕМПЕР ГАЗА ОПАСНАЯ (ДВ/С)
} mfci_signals_word_14_b_t;

//! Слово 15 сигнализации МФЦИ (сигналы ДВ)
typedef struct mfci_signals_word_15_b_t {
   uint16_t dv1_n1_high          : 1; //!< [ДВ1-Л004] ДВ1 ОБОРОТЫ НД ОПАСНЫЕ (ДВ/С)
   uint16_t dv2_n1_high          : 1; //!< [ДВ2-Л004] ДВ2 ОБОРОТЫ НД ОПАСНЫЕ (ДВ/С)
   uint16_t dv3_n1_high          : 1; //!< [ДВ3-Л004] ДВ3 ОБОРОТЫ НД ОПАСНЫЕ (ДВ/С)
   uint16_t dv4_n1_high          : 1; //!< [ДВ4-Л004] ДВ4 ОБОРОТЫ НД ОПАСНЫЕ (ДВ/С)
   uint16_t dv1_n2_high          : 1; //!< [ДВ1-Л005] ДВ1 ОБОРОТЫ ВД ОПАСНЫЕ (ДВ/С)
   uint16_t dv2_n2_high          : 1; //!< [ДВ2-Л005] ДВ2 ОБОРОТЫ ВД ОПАСНЫЕ (ДВ/С)
   uint16_t dv3_n2_high          : 1; //!< [ДВ3-Л005] ДВ3 ОБОРОТЫ ВД ОПАСНЫЕ (ДВ/С)
   uint16_t dv4_n2_high          : 1; //!< [ДВ4-Л005] ДВ4 ОБОРОТЫ ВД ОПАСНЫЕ (ДВ/С)
   uint16_t dv1_reserve_controls : 1; //!< [ДВ1-Л006] ДВ1 ПЕРЕХОД НА РА (ДВ/С)
   uint16_t dv2_reserve_controls : 1; //!< [ДВ2-Л006] ДВ2 ПЕРЕХОД НА РА (ДВ/С)
   uint16_t dv3_reserve_controls : 1; //!< [ДВ3-Л006] ДВ3 ПЕРЕХОД НА РА (ДВ/С)
   uint16_t dv4_reserve_controls : 1; //!< [ДВ4-Л006] ДВ4 ПЕРЕХОД НА РА (ДВ/С)
   uint16_t dv1_gas_temp_high    : 1; //!< [ДВ1-Л007] ДВ1 ТЕМПЕР ГАЗА ПОВЫШЕН (ДВ/С)
   uint16_t dv2_gas_temp_high    : 1; //!< [ДВ2-Л007] ДВ2 ТЕМПЕР ГАЗА ПОВЫШЕН (ДВ/С)
   uint16_t dv3_gas_temp_high    : 1; //!< [ДВ3-Л007] ДВ3 ТЕМПЕР ГАЗА ПОВЫШЕН (ДВ/С)
   uint16_t dv4_gas_temp_high    : 1; //!< [ДВ4-Л007] ДВ4 ТЕМПЕР ГАЗА ПОВЫШЕН (ДВ/С)
} mfci_signals_word_15_b_t;

//! Слово 16 сигнализации МФЦИ (сигналы ДВ, ТОПЛ)
typedef struct mfci_signals_word_16_b_t {
   uint16_t dv1_esud_untested   : 1; //!< [ДВ1-Л008] ДВ1 ЭСУД ПРОВЕРЬ (ДВ/С)
   uint16_t dv2_esud_untested   : 1; //!< [ДВ2-Л008] ДВ2 ЭСУД ПРОВЕРЬ (ДВ/С)
   uint16_t dv3_esud_untested   : 1; //!< [ДВ3-Л008] ДВ3 ЭСУД ПРОВЕРЬ (ДВ/С)
   uint16_t dv4_esud_untested   : 1; //!< [ДВ4-Л008] ДВ4 ЭСУД ПРОВЕРЬ (ДВ/С)
   uint16_t dv1_intake_untested : 1; //!< [ДВ1-Л009] ДВ1 АУ ВЗ ПРОВЕРЬ (ДВ/С)
   uint16_t dv2_intake_untested : 1; //!< [ДВ2-Л009] ДВ2 АУ ВЗ ПРОВЕРЬ (ДВ/С)
   uint16_t dv3_intake_untested : 1; //!< [ДВ3-Л009] ДВ3 АУ ВЗ ПРОВЕРЬ (ДВ/С)
   uint16_t dv4_intake_untested : 1; //!< [ДВ4-Л009] ДВ4 АУ ВЗ ПРОВЕРЬ (ДВ/С)
   uint16_t dv1_dv_active       : 1; //!< [ДВ1-Д027] Двигатель работает
   uint16_t dv2_dv_active       : 1; //!< [ДВ2-Д027] Двигатель работает
   uint16_t dv3_dv_active       : 1; //!< [ДВ3-Д027] Двигатель работает
   uint16_t dv4_dv_active       : 1; //!< [ДВ4-Д027] Двигатель работает
   uint16_t topl_dz_on          : 1; //!< [ТОПЛ-Д001] ТОПЛ АВТ ЗАПРАВКИ ВКЛ (ДВ/С)
   uint16_t topl_dz_failure     : 1; //!< [ТОПЛ-Д002] ТОПЛ АВТ ЗАПРАВКИ ОТКАЗ (ДВ/С)
   uint16_t topl_failure_left   : 1; //!< [ТОПЛ-Д003] ТОПЛ ИЗМЕР ЛЕВ БОРТА ОТКАЗ (ДВ/С)
   uint16_t topl_failure_right  : 1; //!< [ТОПЛ-Д004] ТОПЛ ИЗМЕР ПРАВ БОРТА ОТКАЗ (ДВ/С)
} mfci_signals_word_16_b_t;

//! Слово 17 сигнализации МФЦИ (сигналы ТОПЛ)
typedef struct mfci_signals_word_17_b_t {
   uint16_t dz_lock               : 1; //!< [ТОПЛ-Д005] ДОЗАПРАВКА СЦЕПКА (ДВ/С)
   uint16_t topl_discharge_front  : 1; //!< [ТОПЛ-Д006] ТОПЛ СЛИВ АВАР ПЕРЕДН БАКОВ (ДВ/С)
   uint16_t topl_discharge_rear   : 1; //!< [ТОПЛ-Д007] ТОПЛ СЛИВ АВАР ЗАДН БАКОВ (ДВ/С)
   uint16_t topl_pump_b1l_failure : 1; //!< [ТОПЛ-Д256] ТОПЛ НАСОСЫ Б1Л ОТКАЗ (ДВ/С)
   uint16_t topl_pump_b1r_failure : 1; //!< [ТОПЛ-Д257] ТОПЛ НАСОСЫ Б1П ОТКАЗ (ДВ/С)
   uint16_t topl_pump_b2l_failure : 1; //!< [ТОПЛ-Д258] ТОПЛ НАСОСЫ Б2Л ОТКАЗ (ДВ/С)
   uint16_t topl_pump_b2r_failure : 1; //!< [ТОПЛ-Д259] ТОПЛ НАСОСЫ Б2П ОТКАЗ (ДВ/С)
   uint16_t topl_pump_b3l_failure : 1; //!< [ТОПЛ-Д260] ТОПЛ НАСОСЫ Б3Л ОТКАЗ (ДВ/С)
   uint16_t topl_pump_b3r_failure : 1; //!< [ТОПЛ-Д261] ТОПЛ НАСОСЫ Б3П ОТКАЗ (ДВ/С)
   uint16_t topl_pump_b4l_failure : 1; //!< [ТОПЛ-Д262] ТОПЛ НАСОСЫ Б4Л ОТКАЗ (ДВ/С)
   uint16_t topl_pump_b4r_failure : 1; //!< [ТОПЛ-Д263] ТОПЛ НАСОСЫ Б4П ОТКАЗ (ДВ/С)
   uint16_t topl_pump_b5_failure  : 1; //!< [ТОПЛ-Д264] ТОПЛ НАСОСЫ Б5 ОТКАЗ (ДВ/С)
   uint16_t topl_pump_b6_failure  : 1; //!< [ТОПЛ-Д265] ТОПЛ НАСОСЫ Б6 ОТКАЗ (ДВ/С)
   uint16_t topl_pump_rb1_failure : 1; //!< [ТОПЛ-Д266] ТОПЛ НАСОСЫ РБ1 ОТКАЗ (ДВ/С)
   uint16_t topl_pump_rb2_failure : 1; //!< [ТОПЛ-Д267] ТОПЛ НАСОСЫ РБ2 ОТКАЗ (ДВ/С)
   uint16_t topl_pump_rb3_failure : 1; //!< [ТОПЛ-Д268] ТОПЛ НАСОСЫ РБ3 ОТКАЗ (ДВ/С)
} mfci_signals_word_17_b_t;

//! Слово 18 сигнализации МФЦИ (сигналы ТОПЛ)
typedef struct mfci_signals_word_18_b_t {
   uint16_t topl_pump_rb4_failure         : 1; //!< [ТОПЛ-Д269] ТОПЛ НАСОСЫ РБ4 ОТКАЗ (ДВ/С)
   uint16_t topl_pump_b1l_balance_failure : 1; //!< [ТОПЛ-Д270] ТОПЛ БАЛАНС НАСОСЫ Б1Л ОТКАЗ (ДВ/С)
   uint16_t topl_pump_b1r_balance_failure : 1; //!< [ТОПЛ-Д271] ТОПЛ БАЛАНС НАСОСЫ Б1П ОТКАЗ (ДВ/С)
   uint16_t topl_pump_b5_balance_failure  : 1; //!< [ТОПЛ-Д272] ТОПЛ БАЛАНС НАСОСЫ Б5 ОТКАЗ (ДВ/С)
   uint16_t topl_pump_b6_balance_failure  : 1; //!< [ТОПЛ-Д273] ТОПЛ БАЛАНС НАСОСЫ Б6 ОТКАЗ (ДВ/С)
   uint16_t topl_centering_failure        : 1; //!< [ТОПЛ-Д274] ТОПЛ АВТ ЦЕНТРОВКИ ОТКАЗ (ДВ/С)
   uint16_t topl_consump_failure          : 1; //!< [ТОПЛ-Д275] ТОПЛ АВТ РАСХОДА ОТКАЗ (ДВ/С)
   uint16_t dz_supply_on                  : 1; //!< [ТОПЛ-Д276] Включение питания щитка дозаправки
   uint16_t force_fueling                 : 1; //!< [ТОПЛ-Д285] Принудительная заправка
   uint16_t dz_valve                      : 1; //!< [ТОПЛ-Д287] КЛАПАН ШТАНГИ (ДВ/С)
   uint16_t dz_valve_opened               : 1; //!< [ТОПЛ-Д288] КЛАПАН ОТКРЫТ (ДВ/С)
   uint16_t topl_centering_rear_lim       : 1; //!< [ТОПЛ-Д291] ТОПЛ ЦЕНТРОВКА ЗАДН ПРЕДЕЛ (ДВ/С)
   uint16_t topl_centering_front_lim      : 1; //!< [ТОПЛ-Д292] ТОПЛ ЦЕНТРОВКА ПЕРЕДН ПРЕДЕЛ (ДВ/С)
   uint16_t topl_venting_on               : 1; //!< [ТОПЛ-Д293] ТОПЛ НАСОС ДРЕНАЖА ВКЛ (ДВ/С)
   uint16_t topl_venting_active           : 1; //!< [ТОПЛ-Д294] ТОПЛ ДРЕНАЖ В БАКЕ (ДВ/С)
   uint16_t topl_12t                      : 1; //!< [ТОПЛ-Л002] ТОПЛ ОСТАТОК 12 Т (ДВ/С)
} mfci_signals_word_18_b_t;

//! Слово 19 сигнализации МФЦИ (сигналы ТОПЛ)
typedef struct mfci_signals_word_19_b_t {
   uint16_t topl_rb1_pump1_fail      : 1; //!< [ТОПЛ-Л_Н1РБ1_ОТКАЗ] ТОПЛ НАСОС 1 РБ1 ОТКАЗ (ДВ/С)
   uint16_t topl_rb1_pump2_fail      : 1; //!< [ТОПЛ-Л_Н2РБ1_ОТКАЗ] ТОПЛ НАСОС 2 РБ1 ОТКАЗ (ДВ/С)
   uint16_t topl_rb1_pump3_fail      : 1; //!< [ТОПЛ-Л_Н3РБ1_ОТКАЗ] ТОПЛ НАСОС 3 РБ1 ОТКАЗ (ДВ/С)
   uint16_t topl_rb2_pump1_fail      : 1; //!< [ТОПЛ-Л_Н1РБ2_ОТКАЗ] ТОПЛ НАСОС 1 РБ2 ОТКАЗ (ДВ/С)
   uint16_t topl_rb2_pump2_fail      : 1; //!< [ТОПЛ-Л_Н2РБ2_ОТКАЗ] ТОПЛ НАСОС 2 РБ2 ОТКАЗ (ДВ/С)
   uint16_t topl_rb2_pump3_fail      : 1; //!< [ТОПЛ-Л_Н3РБ2_ОТКАЗ] ТОПЛ НАСОС 3 РБ2 ОТКАЗ (ДВ/С)
   uint16_t topl_rb3_pump1_fail      : 1; //!< [ТОПЛ-Л_Н1РБ3_ОТКАЗ] ТОПЛ НАСОС 1 РБ3 ОТКАЗ (ДВ/С)
   uint16_t topl_rb3_pump2_fail      : 1; //!< [ТОПЛ-Л_Н2РБ3_ОТКАЗ] ТОПЛ НАСОС 2 РБ3 ОТКАЗ (ДВ/С)
   uint16_t topl_rb3_pump3_fail      : 1; //!< [ТОПЛ-Л_Н3РБ3_ОТКАЗ] ТОПЛ НАСОС 3 РБ3 ОТКАЗ (ДВ/С)
   uint16_t topl_rb4_pump1_fail      : 1; //!< [ТОПЛ-Л_Н1РБ4_ОТКАЗ] ТОПЛ НАСОС 1 РБ4 ОТКАЗ (ДВ/С)
   uint16_t topl_rb4_pump2_fail      : 1; //!< [ТОПЛ-Л_Н2РБ4_ОТКАЗ] ТОПЛ НАСОС 2 РБ4 ОТКАЗ (ДВ/С)
   uint16_t topl_rb4_pump3_fail      : 1; //!< [ТОПЛ-Л_Н3РБ4_ОТКАЗ] ТОПЛ НАСОС 3 РБ4 ОТКАЗ (ДВ/С)
   uint16_t topl_valve_pk1_closed_kv : 1; //!< [ТОПЛ-Д141] КВ ЗАКР пожарного крана ПК1 (для счетчика давления азота)
   uint16_t topl_valve_pk2_closed_kv : 1; //!< [ТОПЛ-Д145] КВ ЗАКР пожарного крана ПК2 (для счетчика давления азота)
   uint16_t topl_valve_pk3_closed_kv : 1; //!< [ТОПЛ-Д149] КВ ЗАКР пожарного крана ПК3 (для счетчика давления азота)
   uint16_t topl_valve_pk4_closed_kv : 1; //!< [ТОПЛ-Д153] КВ ЗАКР пожарного крана ПК4 (для счетчика давления азота)
} mfci_signals_word_19_b_t;

//! Слово 20 сигнализации МФЦИ (сигналы ТОПЛ, ПКР)
typedef struct mfci_signals_word_20_b_t {
   uint16_t topl_check_rb1  : 1; //!< [ТОПЛ-Д277] Проверь топливо РБ1 (положение РУД>72° нежелательно, для шкал двигателей)
   uint16_t topl_check_rb2  : 1; //!< [ТОПЛ-Д278] Проверь топливо РБ2 (положение РУД>72° нежелательно, для шкал двигателей)
   uint16_t topl_check_rb3  : 1; //!< [ТОПЛ-Д279] Проверь топливо РБ3 (положение РУД>72° нежелательно, для шкал двигателей)
   uint16_t topl_check_rb4  : 1; //!< [ТОПЛ-Д280] Проверь топливо РБ4 (положение РУД>72° нежелательно, для шкал двигателей)
   uint16_t topl_check      : 1; //!< [ТОПЛ-Л001] ТОПЛ ПРОВЕРЬ (ДВ/С)
   uint16_t speed_high      : 1; //!< [ПКР-Д001] СКОРОСТЬ ВЕЛИКА (ДВ/С)
   uint16_t speed_low       : 1; //!< [ПКР-Д002] СКОРОСТЬ МАЛА (ДВ/С)
   uint16_t ny_high         : 1; //!< [ПКР-Д003] Ny ПРЕДЕЛ (перегрузка выше максимальной, ДВ/С)
   uint16_t ny_low          : 1; //!< [ПКР-Д004] Ny ПРЕДЕЛ (перегрузка ниже минимальной, ДВ/С)
   uint16_t roll_left_high  : 1; //!< [ПКР-Д005] КРЕН ВЕЛИК (левый, ДВ/С)
   uint16_t roll_right_high : 1; //!< [ПКР-Д006] КРЕН ВЕЛИК (правый, ДВ/С)
   uint16_t alpha_high      : 1; //!< [ПКР-Д007] АЛЬФА ПРЕДЕЛ (угол атаки выше максимального, ДВ/С)
   uint16_t alpha_low       : 1; //!< [ПКР-Д008] АЛЬФА ПРЕДЕЛ (угол атаки ниже минимального, ДВ/С)
   uint16_t altitude_appr_1 : 1; //!< [ПКР-Д009] ЭШЕЛОН ПОДХОД (ДВ/С)
   uint16_t altitude_appr_2 : 1; //!< [ПКР-Д012] ЗАДАННАЯ ВЫСОТА ПОДХОД (ДВ/С)
   uint16_t pkr_failure     : 1; //!< [ПКР-Д017] ФУНКЦИИ ПКР ОТКАЗ (ДВ/С)
} mfci_signals_word_20_b_t;

//! Слово 21 сигнализации МФЦИ (сигналы ПКР, САУ)
typedef struct mfci_signals_word_21_b_t {
   uint16_t pkr_alpha_off       : 1; //!< [ПКР-Д018] ПКР НЕТ КОНТРОЛЯ УГЛА АТАКИ (СОСТ)
   uint16_t pkr_speed_min_off   : 1; //!< [ПКР-Д019] ПКР НЕТ КОНТРОЛЯ СКОРОСТИ МИН (СОСТ)
   uint16_t pkr_speed_max_off   : 1; //!< [ПКР-Д020] ПКР НЕТ КОНТРОЛЯ СКОРОСТИ МАКС (СОСТ)
   uint16_t pkr_ny_off          : 1; //!< [ПКР-Д021] ПКР НЕТ КОНТРОЛЯ ПЕРЕГРУЗКИ (СОСТ)
   uint16_t pkr_roll_off        : 1; //!< [ПКР-Д022] ПКР НЕТ КОНТРОЛЯ КРЕНА (СОСТ)
   uint16_t pkr_altitude_off_1  : 1; //!< [ПКР-Д023] ПКР НЕТ КОНТРОЛЯ ЗАДАННОГО ЭШЕЛОНА (СОСТ)
   uint16_t pkr_altitude_off_2  : 1; //!< [ПКР-Д024] ПКР НЕТ КОНТРОЛЯ ЗАДАННОЙ ВЫСОТЫ (СОСТ)
   uint16_t check_altitude      : 1; //!< [ПКР-Л001] ЭШЕЛОН ВЫСОТУ ПРОВЕРЬ (ДВ/С)
   uint16_t ap_failure          : 1; //!< [САУ-Д022] АП ОТКАЗ (ДВ/С)
   uint16_t azp_failure         : 1; //!< [САУ-Д023] АЗП ЗАПРЕЩЕН (ДВ/С)
   uint16_t ap_off              : 1; //!< [САУ-Д024] АП ОТКЛЮЧЕН (ДВ/С)
   uint16_t ap_mode_changed     : 1; //!< [САУ-Д025] АП РЕЖИМ ИЗМЕНЕН (ДВ/С)
   uint16_t at_control          : 1; //!< [САУ-Д026] ТЯГОЙ УПРАВЛЯЙ (ДВ/С)
   uint16_t landing_cathegory_1 : 1; //!< [САУ-Д042] КАТЕГОР ПОСАД1 (СОСТ)
   uint16_t landing_cathegory_2 : 1; //!< [САУ-Д043] КАТЕГОР ПОСАД2 (СОСТ)
   uint16_t sau_manual          : 1; //!< [САУ] ПЕРЕЙДИ НА ШТУРВАЛ (ДВ/С)
} mfci_signals_word_21_b_t;

//! Слово 22 сигнализации МФЦИ (сигналы САУ, АБСУ)
typedef struct mfci_signals_word_22_b_t {
   uint16_t unlock_rud               : 1; //!< [САУ] РУД РАССТОПОРИ (ДВ/С)
   uint16_t dv1_at_off               : 1; //!< [САУ] ДВ1 АТ ОТКЛЮЧЕН (ДВ/С)
   uint16_t dv2_at_off               : 1; //!< [САУ] ДВ2 АТ ОТКЛЮЧЕН (ДВ/С)
   uint16_t dv3_at_off               : 1; //!< [САУ] ДВ3 АТ ОТКЛЮЧЕН (ДВ/С)
   uint16_t dv4_at_off               : 1; //!< [САУ] ДВ4 АТ ОТКЛЮЧЕН (ДВ/С)
   uint16_t dz_pitch                 : 1; //!< [АБСУ-Д024] УПОР ДЗ ТАНГАЖ (ДВ/С)
   uint16_t assu_pitch_failure       : 1; //!< [АБСУ-Л019] АСШУ ТАНГАЖ ОТКАЗ (ДВ/С)
   uint16_t assu_interc_failure      : 1; //!< [АБСУ-Л020] ИНТЕРЦ ОТКАЗ (ДВ/С)
   uint16_t assu_fin_failure         : 1; //!< [АБСУ-Л021] КИЛЬ ОТКАЗ (ДВ/С)
   uint16_t absu_dmp_pitch_failure   : 1; //!< [АБСУ-Д037] АБСУ ДЕМПФЕР ТАНГАЖА ОТКАЗ (СОСТ)
   uint16_t absu_dmp_roll_failure    : 1; //!< [АБСУ-Д038] АБСУ ДЕМПФЕР КРЕНА ОТКАЗ (СОСТ)
   uint16_t absu_dmp_heading_failure : 1; //!< [АБСУ-Д039] АБСУ ДЕМПФЕР КУРСА ОТКАЗ (СОСТ)
   uint16_t absu_ny_invalid          : 1; //!< [АБСУ-Д040] АБСУ ОГРАНИЧЕНИЕ ПО ny ОТКАЗ (СОСТ)
   uint16_t absu_roll_invalid        : 1; //!< [АБСУ-Д041] АБСУ ОГРАНИЧЕНИЕ КРЕНА ОТКАЗ (СОСТ)
   uint16_t absu_stab_off            : 1; //!< [АБСУ-Д042] АБСУ СТАБ ОТКЛЮЧЕН (СОСТ)
   uint16_t absu_fin_off             : 1; //!< [АБСУ-Д043] АБСУ КИЛЬ ОТКЛЮЧЕН (СОСТ)
} mfci_signals_word_22_b_t;

//! Слово 23 сигнализации МФЦИ (сигналы АБСУ)
typedef struct mfci_signals_word_23_b_t {
   uint16_t absu_interc_off           : 1; //!< [АБСУ-Д044] АБСУ ИНТЕРЦ ОТКЛЮЧЕНЫ (СОСТ)
   uint16_t absu_flaperon_off         : 1; //!< [АБСУ-Д045] АБСУ ФЛАП ОТКЛЮЧЕНЫ (СОСТ)
   uint16_t dmp_ra_off_1              : 1; //!< [АБСУ-Д046] АБСУ ДЕМПФЕР РА 1К ОТКЛЮЧЕНЫ (СОСТ)
   uint16_t dmp_ra_off_2              : 1; //!< [АБСУ-Д047] АБСУ ДЕМПФЕР РА 2К ОТКЛЮЧЕНЫ (СОСТ)
   uint16_t dmp_ra_off_3              : 1; //!< [АБСУ-Д048] АБСУ ДЕМПФЕР РА 3К ОТКЛЮЧЕНЫ (СОСТ)
   uint16_t dmp_ra_off_4              : 1; //!< [АБСУ-Д049] АБСУ ДЕМПФЕР РА 4К ОТКЛЮЧЕНЫ (СОСТ)
   uint16_t dau_left_heating_failure  : 1; //!< [АБСУ-Д050] ДАУ ЛЕВ ОБОГРЕВА НЕТ (СОСТ)
   uint16_t dau_right_heating_failure : 1; //!< [АБСУ-Д051] ДАУ ПРАВ ОБОГРЕВА НЕТ (СОСТ)
   uint16_t mb_pitch1_failure         : 1; //!< [АБСУ-Д052] АБСУ МБ ТАНГ КАН 1 ОТКАЗ (СОСТ)
   uint16_t mb_pitch2_failure         : 1; //!< [АБСУ-Д053] АБСУ МБ ТАНГ КАН 2 ОТКАЗ (СОСТ)
   uint16_t mr3_1_failure             : 1; //!< [АБСУ-Д056] АБСУ МРЗ КАН 1 ОТКАЗ (СОСТ)
   uint16_t mr3_2_failure             : 1; //!< [АБСУ-Д057] АБСУ МРЗ КАН 2 ОТКАЗ (СОСТ)
   uint16_t assu_flaperon_failure     : 1; //!< [АБСУ-Л022] АСШУ ФЛАП ОТКАЗ (ДВ/С)
   uint16_t interc                    : 1; //!< [АБСУ-Д065] ИНТРЦ ВЫПУЩЕНЫ (НЕ ГОТОВ К ВЗЛЁТУ)
   uint16_t absu_weight_failure       : 1; //!< [АБСУ-Д066] АБСУ НЕТ ДАННЫХ ПО ВЕСУ (СОСТ)
   uint16_t absu_vsp_failure          : 1; //!< [АБСУ-Д067] АБСУ НЕТ ДАННЫХ ПО ВСП (СОСТ)
} mfci_signals_word_23_b_t;

//! Слово 24 сигнализации МФЦИ (сигналы АБСУ)
typedef struct mfci_signals_word_24_b_t {
   uint16_t absu_flap_failure          : 1; //!< [АБСУ-Д068] АБСУ НЕТ ДАННЫХ ПО ЗАКРЫЛКАМ (СОСТ)
   uint16_t absu_chi_failure           : 1; //!< [АБСУ-Д069] АБСУ НЕТ ДАННЫХ ПО СТРЕЛОВИДНОСТИ (СОСТ)
   uint16_t absu_alpha_failure         : 1; //!< [АБСУ-Д070] АБСУ НЕТ ДАННЫХ ПО УГЛУ АТАКИ (СОСТ)
   uint16_t trimmer_roll_failure       : 1; //!< [АБСУ-Д071] ТРИММЕР КРЕНА ОТКАЗ (ДВ/С)
   uint16_t trimmer_course_failure     : 1; //!< [АБСУ-Д072] ТРИММЕР КУРСА ОТКАЗ (ДВ/С)
   uint16_t trimmer_pitch_failure      : 1; //!< [АБСУ-Д073] ТРИММЕР ТАНГАЖА ОТКАЗ (ДВ/С)
   uint16_t absu_nx_failure            : 1; //!< [АБСУ-Д078] АБСУ ОГРАНИЧЕНИЕ ПО Nх ОТКАЗ (СОСТ)
   uint16_t absu_stab_no_reserve       : 1; //!< [АБСУ-Л001] РА СТАБ РЕЗЕРВА НЕТ (ДВ/С)
   uint16_t absu_fin_no_reserve        : 1; //!< [АБСУ-Л002] РА КИЛЬ РЕЗЕРВА НЕТ (ДВ/С)
   uint16_t absu_flaperon_l_no_reserve : 1; //!< [АБСУ-Л003] РА ФЛАП ЛЕВ РЕЗЕРВА НЕТ (ДВ/С)
   uint16_t absu_flaperon_r_no_reserve : 1; //!< [АБСУ-Л004] РА ФЛАП ПРАВ РЕЗЕРВА НЕТ (ДВ/С)
   uint16_t absu_interc_l_no_reserve   : 1; //!< [АБСУ-Л005] РА ИНТЕРЦ ЛЕВ РЕЗЕРВА НЕТ (ДВ/С)
   uint16_t absu_interc_r_no_reserve   : 1; //!< [АБСУ-Л006] РА ИНТЕРЦ ПРАВ РЕЗЕРВА НЕТ (ДВ/С)
   uint16_t absu_limit                 : 1; //!< [АБСУ-Л007] ОГРАНИЧЬ АЛЬФУ, ny, ГАММУ (ДВ/С)
   uint16_t balance_failure            : 1; //!< [АБСУ-Л008] AВТОБАЛАНС ОТКАЗ (ДВ/С)
   uint16_t set_m09_chi35              : 1; //!< [АБСУ-Л009] ПЕРЕЙДИ М<0.9 ХИ<35 (ДВ/С)
} mfci_signals_word_24_b_t;

//! Слово 25 сигнализации МФЦИ (сигналы АБСУ, СМК)
typedef struct mfci_signals_word_25_b_t {
   uint16_t roll_careful            : 1; //!< [АБСУ-Л010] УПРАВЛЯЙ КРЕНОМ ПЛАВНО (ДВ/С)
   uint16_t set_v900                : 1; //!< [АБСУ-Л011] ПЕРЕЙДИ НА V<900 (ДВ/С)
   uint16_t absu_landing_flap_15    : 1; //!< [АБСУ-Л012] ПОСАДКА ЗАКРЛК 15, V>300 (ДВ/С)
   uint16_t flap_unstable           : 1; //!< [АБСУ-Л013] ЗАКРЛК ПАРИРУЙ (ДВ/С)
   uint16_t bad_side_controls       : 1; //!< [АБСУ-Л014] БОК УПРАВЛ СНИЖЕНО (ДВ/С)
   uint16_t vt_failure              : 1; //!< [АБСУ-Л015] ВОЗД ТОРМ ОТКАЗ (ДВ/С)
   uint16_t pedals_failure          : 1; //!< [АБСУ-Л016] УПРАВЛ ПЕДАЛЯМИ ОТКАЗ (ДВ/С)
   uint16_t roll_no_neutral         : 1; //!< [АБСУ-Л017] КРЕН НЕЙТРАЛИ НЕТ (ДВ/С)
   uint16_t heading_no_neutral      : 1; //!< [АБСУ-Л018] КУРС НЕЙТРАЛИ НЕТ (ДВ/С)
   uint16_t flap_failure            : 1; //!< [СМК-Л001] ЗАКРЛК ОТКАЗ (ДВ/С)
   uint16_t slat_failure            : 1; //!< [СМК-Л002] ПРЕДКР ОТКАЗ (ДВ/С)
   uint16_t flap_correction_failure : 1; //!< [СМК-Л003] ЗАКРЛ-ПРЕДКР КОРРЕКЦИЯ ОТКАЗ (ДВ/С)
   uint16_t flap_track_mode_failure : 1; //!< [СМК-Л005] ЗАКРЛК-ПРЕДКР СЛЕДЯЩ РЕЖИМ ОТКАЗ (ДВ/С)
   uint16_t flap_async              : 1; //!< [СМК-Л007] ЗАКРЛК РАССИНХ (ДВ/С)
   uint16_t slat_async              : 1; //!< [СМК-Л008] ПРЕДКР РАССИНХ (ДВ/С)
   uint16_t flap_not_ready          : 1; //!< [СМК-Л009] ЗАКРЛК НЕВЗЛЕТ (НЕ ГОТОВ К ВЗЛЁТУ)
} mfci_signals_word_25_b_t;

//! Слово 26 сигнализации МФЦИ (сигналы СМК, СК, ТОРМ)
typedef struct mfci_signals_word_26_b_t {
   uint16_t flap_left_slow            : 1; //!< [СМК-Л010] ЗАКРЛ ЛЕВ ЗАТОРМ (ДВ/С)
   uint16_t flap_right_slow           : 1; //!< [СМК-Л011] ЗАКРЛ ПРАВ ЗАТОРМ (ДВ/С)
   uint16_t wing_track_mode_failure   : 1; //!< [СМК-Л012] КРЫЛО СЛЕДЯЩ РЕЖИМ ОТКАЗ (ДВ/С)
   uint16_t wing_failure              : 1; //!< [СМК-Л013] КРЫЛО ОТКАЗ (ДВ/С)
   uint16_t wing_async                : 1; //!< [СМК-Л015] КРЫЛО РАССИНХ (ДВ/С)
   uint16_t seat_pilot_1_moved_back   : 1; //!< [СК-Д001] КРЕСЛО КОМАНДИРА ОТКАТ (ДВ/С)
   uint16_t seat_pilot_2_moved_back   : 1; //!< [СК-Д002] КРЕСЛО ПОМОЩНИКА ОТКАТ (ДВ/С)
   uint16_t main_brakes_failure_1     : 1; //!< [ТОРМ-Д401] ТОРМ ОСН ОТКАЗ (ДВ/С)
   uint16_t emerg_brakes_failure      : 1; //!< [ТОРМ-Д601] ТОРМ РЕЗЕРВ ОТКАЗ (ДВ/С)
   uint16_t emerg_brakes_on           : 1; //!< [ТОРМ-Д603] ТОРМ РЕЗЕРВ ВКЛЮЧЕН (ДВ/С)
   uint16_t brakes_low_accum_pressure : 1; //!< [ТОРМ-Д620] ТОРМ ДАВЛ Г/АКК МАЛО (ДВ/С)
   uint16_t emergency_braking         : 1; //!< [ТОРМ-Д622] ТОРМОЖЕНИЕ АВАРИЙНОЕ (ДВ/С)
   uint16_t auto_brakes_off           : 1; //!< [ТОРМ-Л002] ТОРМ АВТ ОТКЛЮЧЕНО (ДВ/С)
   uint16_t gear_on_brakes            : 1; //!< [ТОРМ-Л004] КОЛЕСА ЗАТОРМОЖЕНЫ (ДВ/С)
   uint16_t start_braking             : 1; //!< [ТОРМ-Л005] СТАРТ ТОРМ ВКЛЮЧЕН (ДВ/С)
   uint16_t parking_brake_on          : 1; //!< [ТОРМ-Л007] СТОЯН ТОРМ ВКЛЮЧЕН (ДВ/С)
} mfci_signals_word_26_b_t;

//! Слово 27 сигнализации МФЦИ (сигналы ТОРМ, СЭС)
typedef struct mfci_signals_word_27_b_t {
   uint16_t auto_brakes_slight       : 1; //!< [ТОРМ-Л008] ТОРМОЖЕНИЕ АВТ СЛАБО (ДВ/С)
   uint16_t auto_brakes_low          : 1; //!< [ТОРМ-Л009] ТОРМОЖЕНИЕ АВТ ПОНИЖ (ДВ/С)
   uint16_t auto_brakes_normal       : 1; //!< [ТОРМ-Л010] ТОРМОЖЕНИЕ АВТ НОРМ (ДВ/С)
   uint16_t brakes_pair_failure      : 1; //!< [ТОРМ-Л011] ТОРМ ОДНА ПАРА ОТКАЗ (СОСТ)
   uint16_t main_brakes_failure_3    : 1; //!< [ТОРМ-Л012] ТОРМ ОСН ОТКАЗ (ДВ/С)
   uint16_t sas_115v_gen1_not_active : 1; //!< [СЭС-Д201] СЭС 115В ГЕН1 НЕ РАБОТАЕТ (СОСТ)
   uint16_t sas_115v_gen2_not_active : 1; //!< [СЭС-Д202] СЭС 115В ГЕН2 НЕ РАБОТАЕТ (СОСТ)
   uint16_t sas_115v_gen3_not_active : 1; //!< [СЭС-Д203] СЭС 115В ГЕН3 НЕ РАБОТАЕТ (СОСТ)
   uint16_t sas_115v_gen4_not_active : 1; //!< [СЭС-Д204] СЭС 115В ГЕН4 НЕ РАБОТАЕТ (СОСТ)
   uint16_t sas_115v_gen1_overload   : 1; //!< [СЭС-Д209] СЭС 115В ГЕН1 ПЕРЕГРУЗКА (СИГН)
   uint16_t sas_115v_gen2_overload   : 1; //!< [СЭС-Д210] СЭС 115В ГЕН2 ПЕРЕГРУЗКА (СИГН)
   uint16_t sas_115v_gen3_overload   : 1; //!< [СЭС-Д211] СЭС 115В ГЕН3 ПЕРЕГРУЗКА (СИГН)
   uint16_t sas_115v_gen4_overload   : 1; //!< [СЭС-Д212] СЭС 115В ГЕН4 ПЕРЕГРУЗКА (СИГН)
   uint16_t sas_115v_partial_left    : 1; //!< [СЭС-Д231] СЭС 115В СЕТЬ ЛЕВ ЧАСТИЧ РЕЖИМ (СИГН)
   uint16_t sas_115v_partial_right   : 1; //!< [СЭС-Д232] СЭС 115В СЕТЬ ПРАВ ЧАСТИЧ РЕЖИМ (СИГН)
   uint16_t sas_115v_connected       : 1; //!< [СЭС-Д233] СЭС 115В СЕТИ СОЕДИНЕНЫ (СИГН)
} mfci_signals_word_27_b_t;

//! Слово 28 сигнализации МФЦИ (сигналы СЭС)
typedef struct mfci_signals_word_28_b_t {
   uint16_t sas_115v_brzu_gen1_failure : 1; //!< [СЭС-Л006] СЭС 115В БРЗУ ГЕН1 ОТКАЗ (СИГН)
   uint16_t sas_115v_brzu_gen2_failure : 1; //!< [СЭС-Л007] СЭС 115В БРЗУ ГЕН2 ОТКАЗ (СИГН)
   uint16_t sas_115v_brzu_gen3_failure : 1; //!< [СЭС-Л008] СЭС 115В БРЗУ ГЕН3 ОТКАЗ (СИГН)
   uint16_t sas_115v_brzu_gen4_failure : 1; //!< [СЭС-Л009] СЭС 115В БРЗУ ГЕН4 ОТКАЗ (СИГН)
   uint16_t sas_115v_brzu_vsu_failure  : 1; //!< [СЭС-Л010] СЭС 115В БРЗУ ГЕН ВСУ ОТКАЗ (СИГН)
   uint16_t sas_115v_transd1_failure   : 1; //!< [СЭС-Л011] СЭС 115В ПРЕОБР1 НЕ РАБОТАЕТ (СОСТ)
   uint16_t sas_115v_transd3_failure   : 1; //!< [СЭС-Л013] СЭС 115В ПРЕОБР3 НЕ РАБОТАЕТ (СОСТ)
   uint16_t sas_115v_turn_off_ppo_gen1 : 1; //!< [СЭС-Л018] СЭС 115В ППО ГЕН1 ОТКЛЮЧИ (СИГН)
   uint16_t sas_115v_turn_off_ppo_gen2 : 1; //!< [СЭС-Л019] СЭС 115В ППО ГЕН2 ОТКЛЮЧИ (СИГН)
   uint16_t sas_115v_turn_off_ppo_gen3 : 1; //!< [СЭС-Л020] СЭС 115В ППО ГЕН3 ОТКЛЮЧИ (СИГН)
   uint16_t sas_115v_turn_off_ppo_gen4 : 1; //!< [СЭС-Л021] СЭС 115В ППО ГЕН4 ОТКЛЮЧИ (СИГН)
   uint16_t sas_27v_connected          : 1; //!< [СЭС-Д325] СЭС 27В СЕТИ СОЕДИНЕНЫ (СИГН)
   uint16_t sas_27v_gen1_not_active    : 1; //!< [СЭС-Д301] СЭС 27В Г1 НЕ РАБОТАЕТ (СОСТ)
   uint16_t sas_27v_gen2_not_active    : 1; //!< [СЭС-Д302] СЭС 27В Г2 НЕ РАБОТАЕТ (СОСТ)
   uint16_t sas_27v_gen3_not_active    : 1; //!< [СЭС-Д303] СЭС 27В Г3 НЕ РАБОТАЕТ (СОСТ)
   uint16_t sas_27v_gen4_not_active    : 1; //!< [СЭС-Д304] СЭС 27В Г4 НЕ РАБОТАЕТ (СОСТ)
} mfci_signals_word_28_b_t;

//! Слово 29 сигнализации МФЦИ (сигналы СЭС)
typedef struct mfci_signals_word_29_b_t {
   uint16_t sas_27v_gen1_overload     : 1; //!< [СЭС-Д309] СЭС 27В Г1 ПЕРЕГРУЗКА (СИГН)
   uint16_t sas_27v_gen2_overload     : 1; //!< [СЭС-Д310] СЭС 27В Г2 ПЕРЕГРУЗКА (СИГН)
   uint16_t sas_27v_gen3_overload     : 1; //!< [СЭС-Д311] СЭС 27В Г3 ПЕРЕГРУЗКА (СИГН)
   uint16_t sas_27v_gen4_overload     : 1; //!< [СЭС-Д312] СЭС 27В Г4 ПЕРЕГРУЗКА (СИГН)
   uint16_t sas_27v_left_on_battery   : 1; //!< [СЭС-Д321] СЭС 27В СЕТЬ ЛЕВ ОТ АКК (СИГН)
   uint16_t sas_27v_right_on_battery  : 1; //!< [СЭС-Д322] СЭС 27В СЕТЬ ПРАВ ОТ АКК (СИГН)
   uint16_t sas_27v_left_partial      : 1; //!< [СЭС-Д323] СЭС 27В СЕТЬ ЛЕВ ЧАСТИЧ РЕЖИМ (СИГН)
   uint16_t sas_27v_right_partial     : 1; //!< [СЭС-Д324] СЭС 27В СЕТЬ ПРАВ ЧАСТИЧ РЕЖИМ (СИГН)
   uint16_t sas_27v_turn_off_battery1 : 1; //!< [СЭС-Л014] СЭС 27В АКК1 ОТКЛЮЧИ (СИГН)
   uint16_t sas_27v_turn_off_battery2 : 1; //!< [СЭС-Л015] СЭС 27В АКК2 ОТКЛЮЧИ (СИГН)
   uint16_t sas_27v_battery1_off      : 1; //!< [СЭС-Л016] СЭС 27В АКК1 ОТКЛЮЧЕН (СОСТ)
   uint16_t sas_27v_battery2_off      : 1; //!< [СЭС-Л017] СЭС 27В АКК2 ОТКЛЮЧЕН (СОСТ)
   uint16_t sas_27v_turn_off_gen1     : 1; //!< [СЭС-Л022] СЭС 27В Г1 ОТКЛЮЧИ (СИГН)
   uint16_t sas_27v_turn_off_gen2     : 1; //!< [СЭС-Л023] СЭС 27В Г2 ОТКЛЮЧИ (СИГН)
   uint16_t sas_27v_turn_off_gen3     : 1; //!< [СЭС-Л024] СЭС 27В Г3 ОТКЛЮЧИ (СИГН)
   uint16_t sas_27v_turn_off_gen4     : 1; //!< [СЭС-Л025] СЭС 27В Г4 ОТКЛЮЧИ (СИГН)
} mfci_signals_word_29_b_t;

//! Слово 30 сигнализации МФЦИ (сигналы ГС)
typedef struct mfci_signals_word_30_b_t {
   uint16_t gs_crossfeeding        : 1; //!< [ГС-Д033] ГС КРАНЫ КОЛЬЦ ВКЛ (НЕ ГОТОВ К ВЗЛЁТУ)
   uint16_t gs_tgt_circuit_failure : 1; //!< [ГС-Д034] КОНТУР ТЖТ ОТКАЗ (ДВ/С)
   uint16_t gs_tgt_pump_failure    : 1; //!< [ГС-Д035] НАСОС ТЖТ ОТКАЗ (ДВ/С)
   uint16_t gs1_failure            : 1; //!< [ГС-Л005] ГС1 ОТКАЗ (ДВ/С)
   uint16_t gs2_failure            : 1; //!< [ГС-Л006] ГС2 ОТКАЗ (ДВ/С)
   uint16_t gs3_failure            : 1; //!< [ГС-Л007] ГС3 ОТКАЗ (ДВ/С)
   uint16_t gs4_failure            : 1; //!< [ГС-Л008] ГС4 ОТКАЗ (ДВ/С)
   uint16_t gs2_pump1_off          : 1; //!< [ГС-Л047] ГС2 Н1 ОТКЛЮЧЕН (ДВ/С)
   uint16_t gs1_pump2_off          : 1; //!< [ГС-Л048] ГС1 Н2 ОТКЛЮЧЕН (ДВ/С)
   uint16_t gs2_pump3_off          : 1; //!< [ГС-Л049] ГС2 Н3 ОТКЛЮЧЕН (ДВ/С)
   uint16_t gs1_pump4_off          : 1; //!< [ГС-Л050] ГС1 Н4 ОТКЛЮЧЕН (ДВ/С)
   uint16_t gs4_pump5_off          : 1; //!< [ГС-Л051] ГС4 Н5 ОТКЛЮЧЕН (ДВ/С)
   uint16_t gs3_pump6_off          : 1; //!< [ГС-Л052] ГС3 Н6 ОТКЛЮЧЕН (ДВ/С)
   uint16_t gs4_pump7_off          : 1; //!< [ГС-Л053] ГС4 Н7 ОТКЛЮЧЕН (ДВ/С)
   uint16_t gs3_pump8_off          : 1; //!< [ГС-Л054] ГС3 Н8 ОТКЛЮЧЕН (ДВ/С)
   uint16_t dv_pumps_failure       : 1; //!< [ОС-Л020] Г/НАСОСЫ ДВ ОТКЛ (НЕ ГОТОВ К ВЗЛЁТУ)
} mfci_signals_word_30_b_t;
